// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRXWlmeYZFW0nYPWo5GctEW-6-G3F3ug',
    appId: '1:714316853778:android:8a24fb17b51cc71c885ecb',
    messagingSenderId: '714316853778',
    projectId: 'services-c8c8d',
    databaseURL: 'https://services-c8c8d-default-rtdb.firebaseio.com',
    storageBucket: 'services-c8c8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsfY1CJN56_uFbUE_NGPPvLU-pLzcSvQ',
    appId: '1:714316853778:ios:aaee84509487933d885ecb',
    messagingSenderId: '714316853778',
    projectId: 'services-c8c8d',
    databaseURL: 'https://services-c8c8d-default-rtdb.firebaseio.com',
    storageBucket: 'services-c8c8d.firebasestorage.app',
    androidClientId: '714316853778-huo0838a1j55m5nsvhtdps9qpedatovr.apps.googleusercontent.com',
    iosClientId: '714316853778-mc4vkasm12712q0q7r3egt7s95rdrjhl.apps.googleusercontent.com',
    iosBundleId: 'com.liztogo.deliveryuser',
  );

}